services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    networks:
      - my-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8080"
    networks:
      - my-network
    depends_on:
      - config-server

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - eureka-server
      - postgres

  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network
    depends_on:
      - user-service
      - postgres

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - company-service

  postgres-user:
    image: 'postgres:14'
    container_name: postgres-user
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=aliya
      - POSTGRES_PASSWORD=aliya123
    ports:
      - "5432:5432"
    networks:
      - my-network


  postgres-company:
    image: 'postgres:14'
    container_name: postgres-company
    environment:
      - POSTGRES_DB=company_db
      - POSTGRES_USER=aliya
      - POSTGRES_PASSWORD=aliya123
    ports:
      - "5433:5432"
    networks:
      - my-network

