services:
  configserver:
    build:
      context: ./configServer
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    networks:
      - my-network

  eurekaserver:
    build:
      context: ./eurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8080"
    networks:
      - my-network
    depends_on:
      - configserver

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
    depends_on:
      - eurekaserver
      - postgres

  companyservice:
    build:
      context: ./companyService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - my-network
    depends_on:
      - userservice
      - postgres

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - companyservice

  postgres:
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=company_db
      - POSTGRES_USER=aliya
      - POSTGRES_PASSWORD=aliya123
    ports:
      - "5433:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
