server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/company_db/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

config:
  uri: http://localhost:8888
