server:
  port: 8080

spring:
  application:
    name: gateway

  config:
    import: optional:config-server:http://localhost:8888

  cloud:
    config:
      fail-fast: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
