spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5433/company_db
    username: aliya
    password: aliya123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082


#version: "3.8"
#
#services:
#  postgres:
#    image: postgres:15
#    container_name: postgres
#    ports:
#      - "5433:5432"
#    environment:
#      POSTGRES_DB: company_db
#      POSTGRES_USER: aliya
#      POSTGRES_PASSWORD: aliya123