spring:
  application:
    name: company-service
  config:
    import: optional:configserver:http://localhost:8888  # <== ПРАВИЛЬНЫЙ СИНТАКСИС
  datasource:
    url: jdbc:postgresql://postgres:5433/company_db
    username: aliya
    password: aliya123

server:
  port: 8082



