server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    # отключаем получение внешней конфигурации, чтобы избежать зависимости от config-server
    enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  endpoints:
    web:
      exposure:
        include: health,info





