server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aliyagabbassova/spring-cloud-config-repo
          default-label: main
          clone-on-start: true